# Generated by Django 2.0.6 on 2019-09-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Color', models.IntegerField(default=0)),
                ('Gender', models.CharField(max_length=200)),
            ],
        ),
    ]
