# Generated by Django 2.0.6 on 2019-09-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='Breed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='Gender',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
